# Generated by Django 5.2 on 2025-04-21 16:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='name',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='start_date',
        ),
        migrations.AddField(
            model_name='challenge',
            name='calories_target',
            field=models.PositiveIntegerField(blank=True, help_text='Target calories to burn', null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='challenged',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challenge',
            name='challenger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challenge',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challenge',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='duration',
            field=models.PositiveIntegerField(default=30, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='challenge',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or requirements'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='challenge',
            name='workout_type',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Strength Training'), ('flexibility', 'Flexibility'), ('hiit', 'HIIT'), ('other', 'Other')], default='cardio', max_length=20),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
