# Generated by Django 4.2.18 on 2025-04-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_alter_challenge_options_remove_challenge_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance in km', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='reps',
            field=models.IntegerField(blank=True, help_text='Number of repetitions', null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='sets',
            field=models.IntegerField(blank=True, help_text='Number of sets', null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True),
        ),
    ]
