# Generated by Django 4.2.18 on 2025-04-24 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_remove_workout_distance_remove_workout_reps_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coachsuggestion',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='coachsuggestion',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coachsuggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
