# Generated by Django 5.2 on 2025-04-27 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_add_initial_achievements'),
        ('fitness', '0006_alter_coachsuggestion_options_and_more'),
    ]

    operations = [
    ]
