# Generated by Django 5.2 on 2025-04-29 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_merge_20250427_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='badge_image',
            field=models.ImageField(blank=True, null=True, upload_to='achievement_badges/'),
        ),
    ]
